version: '2.4'
services:
  backend:
    image: node:16-alpine
    working_dir: /app
    command: sh -c "npx knex migrate:latest && npx knex seed:run && npm run start:dev"
    user: node
    volumes:
      - ./:/app:cached
    environment:
      - NODE_ENV=development
      - DB_URL=postgres://admin:secret@postgres:5432/dev
      - ACCESS_TOKEN_KEY=1c5524827b5e4792feed92debfdce7db2a5e502fb13807cc5fc10849186717071cb88b1f563cd8e17bb19cfd25e697f89b532bc9690806b163d63dcda93cde5a
      - ACCESS_TOKEN_EXPIRATION_TIME=60m
    depends_on:
      - postgres
    ports:
      - 3000:3000
  postgres:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=dev
    ports:
      - 5432:5432
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - '5050:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: developer@dev.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - postgres
